plugins { id 'com.android.application' }

android {
    namespace 'com.youssef.prayeroverlay'
    compileSdk 35
    defaultConfig {
        applicationId 'com.youssef.prayeroverlay'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.batoulapps.adhan:adhan:1.2.1'
}
